#!/usr/bin/env bash
# Copies a file from client (local machine) to remote server
# Check that script receives 3 parameters
if [ "$#" -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
scp -o StrictHostKeyChecking=no -i "${PATH_TO_SSH_KEY}" "${PATH_TO_FILE}" "${USERNAME}@${SERVER_IP}:~/"
